name: CI/CD with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configurar JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compilar y empaquetar con Maven
      run: mvn -B package --file ./pom.xml
    - name: Subir .jar
      uses: actions/upload-artifact@v1
      with:
        name: backend_netflix
        path: ./target/netflix_api-0.0.1.jar
